### ISSUE TITLE
Possible Feature: Retrieving Product Keys and possibly other Metadata

### ISSUE THREAD

**Issue by camelusminimus** [smbl64/humble-cli#57]
A few years back I [dabbled with some R code](https://github.com/camelusminimus/humblebundleR) to retrieve Metadata about my previously bought bundles...

One rather interesting aspect was that I could download a list of all steam keys I had not requested (or rather I could download a list of all possibly available steam keys, and then filter out those where the api actually returned a steam key)

Would it be interesting to implement a feature enabling this use case in `humble-cli`?

I could imagine a subcommand like `humble-cli download-meta -f yaml <bundle_id>` that would write `humble-meta.yaml`(json/csv) file into the same directory structure (per bundle and per download_item) that the downloads are written into today.

A lot of that information can be made available already using the `humble-cli details` command, though using a tree-like data structure like yaml/json would make it easier to be (much) more verbose.

If the format would be "defined" using json-schema, i.e. not only a copy of the current humble bundle REST responses but maybe a little bit more thought out? (Aspects to maybe thing about could be for example how to handle metadata for file versions that change? Would it make sense to update such a metadata file and keep a "previous-versions" data structure?)

Anyways, I would be interested to gage interest in and the relevance/realism of such a feature?

**Comment by smbl64** [comment]
I actually had a similar idea in mind for the `list` subcommand, to have a flag to specify if a json / yaml output is desired.

For example:

```
humble-cli list --format yaml
```

But since I didn't have any actual use for it and nobody asked for it, I didn't work on it.

It should be rather easy to implement. The only thing that comes to my mind is that the [models defined here](https://github.com/smbl64/humble-cli/blob/master/src/models.rs#L32) are not exact 1-to-1 mapping to HB JSON responses. So some fields might be missing.

Other than that, I think `serde` can easily handle serializing data to json or yaml.
